#!/usr/bin/env bash
# FizzBuzz - same line output
a=1
while [ $a -le 100 ]
do
    if (( a % 3 == 0 && a % 5 == 0 )); then
        printf "FizzBuzz "
    elif (( a % 3 == 0 )); then
        printf "Fizz "
    elif (( a % 5 == 0 )); then
        printf "Buzz "
    else
        printf "$a "
    fi
    ((a++))
done
printf "\n"
